---
version: "2.0"

services:
  tierpulse:
    image: ghcr.io/toxmon/tier-pulse:b125092
    env:
      - TIERPULSE_STUB_DB=1
    expose:
      - port: 8888
        as: 80
        to:
          - global: true

profiles:
  compute:
    tierpulse:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 1Gi

  placement:
    akash:
      pricing:
        tierpulse:
          denom: uact
          amount: 1000

deployment:
  tierpulse:
    akash:
      profile: tierpulse
      count: 1
